# Resources { .unnumbered }

## `All Contributors`

- All Contributors documentation: [https://allcontributors.org/docs/en/overview](https://allcontributors.org/docs/en/overview)

## `click`

- `click` documentation: [https://click.palletsprojects.com/en/8.1.x/](https://click.palletsprojects.com/en/8.1.x/)

## DOI to BibTeX conversion

- DOI to BibTeX converter: [https://www.bibtex.com/c/doi-to-bibtex-converter/](https://www.bibtex.com/c/doi-to-bibtex-converter/)

## `GitHub`

- Creating a GitHub issue: [https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue)
- Creating a pull request: [https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
- GitHub Actions documentation: [https://docs.github.com/en/actions](https://docs.github.com/en/actions)
- Repository forks: [https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo)

## `JSpecies`

- `JSpeciesWS` online service: [https://jspecies.ribohost.com/jspeciesws/#home](https://jspecies.ribohost.com/jspeciesws/#home)

## `MUMmer`

- MUMmer3 manual: [https://mummer.sourceforge.net/manual/](https://mummer.sourceforge.net/manual/)
  - `.delta` output format: [https://mummer.sourceforge.net/manual/#nucmeroutput](https://mummer.sourceforge.net/manual/#nucmeroutput)
  - `show-coords` with description of output format: [https://mummer.sourceforge.net/manual/#coords](https://mummer.sourceforge.net/manual/#coords)

### Publications

- @Kurtz2004-ut

## `Quarto`

- The Quarto project: [https://quarto.org/](https://quarto.org/)
- The Quarto guide: [https://quarto.org/docs/guide/](https://quarto.org/docs/guide/)
- Publishing Quarto on GitHub pages: [https://quarto.org/docs/publishing/github-pages.html](https://quarto.org/docs/publishing/github-pages.html)

## `R`/`RStudio`

- `RStudio` Desktop: [https://posit.co/download/rstudio-desktop/](https://posit.co/download/rstudio-desktop/)

## `rich`

- `rich` documentation: [https://rich.readthedocs.io/en/stable/introduction.html](https://rich.readthedocs.io/en/stable/introduction.html)

## `SQLite3`

- [`aiosqlite`](https://github.com/omnilib/aiosqlite): library for asynchronous access to `sqlite3`
- Python `sqlite3` module: [https://docs.python.org/3/library/sqlite3.html](https://docs.python.org/3/library/sqlite3.html)
  - Threadsafety in the `sqlite3` module: [https://docs.python.org/3/library/sqlite3.html#sqlite3.threadsafety](https://docs.python.org/3/library/sqlite3.html#sqlite3.threadsafety)
- Threadsafe modes with `sqlite3`: [https://www.sqlite.org/threadsafe.html](https://www.sqlite.org/threadsafe.html)


## `Visual Studio Code`

- `Visual Studio Code`: [https://code.visualstudio.com/](https://code.visualstudio.com/)